#!/bin/bash
# Add a Date: header to an RFC822 message based on the file date and time
set -e
if [[ -z "$1" || -n "$2" ]]; then
    echo Usage: $0 messagefile
    exit 1
fi
if [[ -n "$(sed -n -e '1,/^$/s/^Date:/EXISTING/pi' "$1")" ]]; then
    echo Warning: Date: line already exists 1>&2
else
    printf 'Date: '
    date -R -d @$(stat -c '%Y'  "$1")
fi
cat "$1"
